### ISSUE TITLE
late submission for day 16

### ISSUE THREAD

**Issue by oringejooz** [upesacm/21DaysOfCode-2024#1209]
late submission for day 16

_Originally posted by @Aahanaaa13 in https://github.com/upesacm/21DaysOfCode-2024/issues/1185#issuecomment-2212563792_
          
![image](https://user-images.githubusercontent.com/124855325/346367098-3c7da63e-4715-4496-9d66-69694a0dd0b8.png)

Hey, it wasn't a late submission, I couldn't create a new PR for Day 17 since you guys didn't merge the stuff and it got re opened as Day 16 PR. SO correct it...please

thanks

**Comment by Arikiver** [comment]
![image](https://github.com/upesacm/21DaysOfCode-2024/assets/138292124/87624e6e-3111-4f60-b52c-009f7bb1b552)

**Comment by oringejooz** [comment]
![image](https://github.com/upesacm/21DaysOfCode-2024/assets/124855325/8b83a283-8797-452e-8d88-d323a005fdc7)
How it feels to be marked as late 
(I hope this small meme doesn't bother you guys)
